FROM jupyter/r-notebook

# For details on the base image:
#   https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-r-notebook
#
# Additional packages should be installed here.

